### PR TITLE
Updates to fix missing NetCDF Fortran includes

### PR DESCRIPTION
**Pull request by sdeastham**
This commit will allow compatibility with MAPL 2.5.0, and is one of several PRs being performed with that in mind.

### CODE REVIEW

**Comment by WilliamDowns** [comment]
FYI for some reason I needed to move including `${NETCDF_F77_INCLUDE_DIR})` into its own IF ...`/netcdf.inc` EXISTS block to get everything to compile. Not sure why I didn't need to edit this include in any of the other modified submodules.

**Comment by lizziel** [comment]
@LiamBindle , could you weigh in on this PR?

**Comment by WilliamDowns** [comment]
Something odd is occurring with finding Spack-built NetCDF libraries in newer MAPL versions that extends beyond this change to FMS. Trying to figure out exactly what the issue is.

**Comment by WilliamDowns** [comment]
My NetCDF library issues were resolved by updating all submodules as described in the update for 2.6.4, so some update between 2.5 and 2.6.4 must have fixed it.

**Comment by lizziel** [comment]
Okay, thanks @WilliamDowns for the update. I will bring this update into our current version of FMS. FYI, that version is still very old, as are our other advection-related repos. I am going to hold off on updating version numbers for FMS, FVdycoreCubed_GridComp, and GFDL_atmos_cubed_sphere (fvdycore submodule in FV) pending validation of new MAPL.

**Pull request merged**
